Repository microsoft/mu_rust_pi, pull requests merged in 2024-09, with the labels that each got.

#18 Add MemoryTypeInfo HOB definitions
  src/hob.rs
Labels: type:documentation

#20 Add definitions for compression type values.
  src/fw_fs/ffs/section.rs
Labels: impact:non-functional

#21 Adds a test for SectionMetadata parsing and fixes an issue with GUID_DEFINED section parsing.
  src/fw_fs.rs
Labels: impact:testing

#22 Add Additional PI Status Codes
  cspell.json
  src/lib.rs
  src/protocols/status_code.rs
  src/status_code.rs
Labels: impact:non-functional, type:enhancement, impact:breaking-change

#24 Cargo.toml: Update version to 4.0
  Cargo.toml
Labels: semver:patch, impact:non-functional

#25 status_code: Fix clippy failures
  src/status_code.rs
Labels: impact:non-functional, type:bug

#26 Refactor Boot Mode
  src/boot_mode.rs
  src/hob.rs
  src/lib.rs
Labels: impact:non-functional, impact:breaking-change, type:documentation
