Repository microsoft/mu_rust_pi, pull requests merged in 2025-02, with the labels that each got.

#47 Fix GuidHob bug and rework relocate_hobs.
  Cargo.toml
  src/hob.rs
Labels: impact:non-functional, type:bug

#52 hob: Do not run get_c_hob_list_size() example
  src/hob.rs
Labels: impact:testing, impact:non-functional, type:documentation, type:bug

#54 fw_fs: Fix broken intra cargo doc links
  src/fw_fs.rs
Labels: impact:non-functional, type:documentation, type:bug

#53 Add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: impact:non-functional

#55 protocols: Add MM Communication protocols
  cspell.json
  src/protocols.rs
  src/protocols/communication.rs
  src/protocols/communication2.rs
  src/protocols/communication3.rs
Labels: type:documentation

#58 rust-toolchain.toml: Add cargo-release
  rust-toolchain.toml
Labels: impact:non-functional
